### ISSUE TITLE
Wrong dir `include`  if tag `CONFIGURATION_NAME` is set

### ISSUE THREAD

**Issue by es20490446e** [Martchus/cpp-utilities#25]
While building, if you add the flag `CONFIGURATION_NAME`, headers install into:

`/usr/include/c++utilities-whatever/c++utilities`

Instead of:

`/usr/include/c++utilities-whatever`

**Comment by Martchus** [comment]
This is correct behavior and important so includes like `#include <c++utilities/application/global.h>` still work - because that's how one is supposed to use headers of this library from external projects. If you use the CMake module or pkg-config correctly then the include path should be added automatically. Otherwise just add it as needed.

**Comment by Martchus** [comment]
Considering that Debian packaging is using this feature I doubt it is buggy. If you nevertheless think so please provide more details to reproduce.

**Comment by es20490446e** [comment]
Let me have a look 👀

**Comment by es20490446e** [comment]
Okay, I figured it out by reading into the [Debian package](https://packages.debian.org/sid/libmartchus-qtutilities-dev) and `CMakeLists.txt`.

While running `cmake` I had to add the flag `CONFIGURATION_PACKAGE_SUFFIX`.

I don't understand that while reading [buildvariables.md](https://github.com/Martchus/cpp-utilities/blob/master/doc/buildvariables.md).

It says:

> * Set CONFIGURATION_PACKAGE_SUFFIX to use libraries built with CONFIGURATION_NAME.

I guess it shall say something like:

> * Set PACKAGE_NAMESPACE_PREFIX to look for library headers with a custom prefix.
> * Set CONFIGURATION_PACKAGE_SUFFIX to look for library headers with a custom suffix.

**Comment by Martchus** [comment]
It should not say anything about headers because that's too specific. This is about all kinds of files the library consists of (the library itself, CMake modules, scripts, …).

`PACKAGE_NAMESPACE_PREFIX` should have documentation. This feature has been contributed by Debian and they didn't add documentation at the time.

**Comment by es20490446e** [comment]
It can say: "for example headers".

**Comment by Martchus** [comment]
I've just pushed a documentation change. So I suppose this issue can be closed.

**Comment by es20490446e** [comment]
Thanks! 👌
