### ISSUE TITLE
Tests fail to run: Could not find executable /usr/ports/devel/cpp-utilities/work/.build/c++utilities_tests

### ISSUE THREAD

**Issue by yurivict** [Martchus/cpp-utilities#26]
It is unclear how c++utilities_tests can be built, since there's no option that enables tests, and the standard cmake option ```BUILD_TESTING``` doesn't work.

**Comment by Martchus** [comment]
Tests are not built by default. I didn't know that there's the standard variable `BUILD_TESTING` so I used `EXCLUDE_TESTS_FROM_ALL` in my project. Set it to `OFF` to build tests by default as [documented](https://martchus.no-ip.biz/doc/c%2B%2Butilities/md_doc_2buildvariables.html). Since this is most useful for development it is also set this way when setting `ENABLE_DEVEL_DEFAULTS` to `ON`.

For packaging I recommend to not set any special variables and instead invoke the `check` target which builds and runs tests. As suggested in the README, checkout my [PKGBUILDs](https://github.com/Martchus/PKGBUILDs/blob/master/c%2B%2Butilities/default/PKGBUILD) repo for packaging examples.

**Comment by yurivict** [comment]
Ok, thanks.
